-- =============================================================
-- V27: CRM / Musteri Iletisim veri hacmini buyutme
-- Yeni kampanyalar + yeni hesaplar icin hedef/mesaj kayitlari.
-- =============================================================

INSERT INTO campaigns (kampanya_adi, baslangic_tarihi, bitis_tarihi, durum) VALUES
    (N'Yaz Kampanyasi 2026', '2026-07-01', '2026-08-31', 'AKTIF'),
    (N'Emeklilik Bilgilendirme', '2026-06-01', '2026-06-30', 'TAMAMLANDI');

INSERT INTO campaign_targets (campaign_id, account_id, onay_durumu) VALUES
    (4, 29, 'ONAYLADI'),
    (5, 30, 'ONAYLAMADI'),
    (4, 31, 'BEKLIYOR'),
    (5, 32, 'AKSIYON_ALMADI'),
    (4, 33, 'ONAYLADI'),
    (5, 34, 'ONAYLAMADI'),
    (4, 35, 'BEKLIYOR'),
    (5, 36, 'AKSIYON_ALMADI'),
    (4, 37, 'ONAYLADI'),
    (5, 38, 'ONAYLAMADI'),
    (4, 39, 'BEKLIYOR'),
    (5, 40, 'AKSIYON_ALMADI'),
    (4, 41, 'ONAYLADI'),
    (5, 42, 'ONAYLAMADI'),
    (4, 43, 'BEKLIYOR'),
    (5, 44, 'AKSIYON_ALMADI'),
    (4, 45, 'ONAYLADI'),
    (5, 46, 'ONAYLAMADI'),
    (4, 47, 'BEKLIYOR'),
    (5, 48, 'AKSIYON_ALMADI'),
    (4, 49, 'ONAYLADI'),
    (5, 50, 'ONAYLAMADI'),
    (4, 51, 'BEKLIYOR'),
    (5, 52, 'AKSIYON_ALMADI'),
    (4, 53, 'ONAYLADI'),
    (5, 54, 'ONAYLAMADI'),
    (4, 55, 'BEKLIYOR'),
    (5, 56, 'AKSIYON_ALMADI'),
    (4, 57, 'ONAYLADI'),
    (5, 58, 'ONAYLAMADI'),
    (4, 59, 'BEKLIYOR'),
    (5, 60, 'AKSIYON_ALMADI'),
    (4, 61, 'ONAYLADI'),
    (5, 62, 'ONAYLAMADI'),
    (4, 63, 'BEKLIYOR'),
    (5, 64, 'AKSIYON_ALMADI'),
    (4, 65, 'ONAYLADI'),
    (5, 66, 'ONAYLAMADI'),
    (4, 67, 'BEKLIYOR'),
    (5, 68, 'AKSIYON_ALMADI'),
    (4, 69, 'ONAYLADI'),
    (5, 70, 'ONAYLAMADI'),
    (4, 71, 'BEKLIYOR'),
    (5, 72, 'AKSIYON_ALMADI'),
    (4, 73, 'ONAYLADI'),
    (5, 74, 'ONAYLAMADI'),
    (4, 75, 'BEKLIYOR'),
    (5, 76, 'AKSIYON_ALMADI'),
    (4, 77, 'ONAYLADI'),
    (5, 78, 'ONAYLAMADI'),
    (4, 79, 'BEKLIYOR'),
    (5, 80, 'AKSIYON_ALMADI'),
    (4, 81, 'ONAYLADI'),
    (5, 82, 'ONAYLAMADI'),
    (4, 83, 'BEKLIYOR'),
    (5, 84, 'AKSIYON_ALMADI'),
    (4, 85, 'ONAYLADI'),
    (5, 86, 'ONAYLAMADI'),
    (4, 87, 'BEKLIYOR'),
    (5, 88, 'AKSIYON_ALMADI'),
    (4, 89, 'ONAYLADI'),
    (5, 90, 'ONAYLAMADI'),
    (4, 91, 'BEKLIYOR'),
    (5, 92, 'AKSIYON_ALMADI'),
    (4, 93, 'ONAYLADI'),
    (5, 94, 'ONAYLAMADI'),
    (4, 95, 'BEKLIYOR'),
    (5, 96, 'AKSIYON_ALMADI'),
    (4, 97, 'ONAYLADI'),
    (5, 98, 'ONAYLAMADI'),
    (4, 99, 'BEKLIYOR'),
    (5, 100, 'AKSIYON_ALMADI'),
    (4, 101, 'ONAYLADI'),
    (5, 102, 'ONAYLAMADI'),
    (4, 103, 'BEKLIYOR'),
    (5, 104, 'AKSIYON_ALMADI'),
    (4, 105, 'ONAYLADI'),
    (5, 106, 'ONAYLAMADI'),
    (4, 107, 'BEKLIYOR'),
    (5, 108, 'AKSIYON_ALMADI'),
    (4, 109, 'ONAYLADI'),
    (5, 110, 'ONAYLAMADI'),
    (4, 111, 'BEKLIYOR'),
    (5, 112, 'AKSIYON_ALMADI'),
    (4, 113, 'ONAYLADI'),
    (5, 114, 'ONAYLAMADI'),
    (4, 115, 'BEKLIYOR'),
    (5, 116, 'AKSIYON_ALMADI'),
    (4, 117, 'ONAYLADI'),
    (5, 118, 'ONAYLAMADI');

INSERT INTO messages (campaign_id, account_id, kanal, icerik, durum) VALUES
    (4, 29, 'SMS', N'Yaz kampanyamiza katiliminiz icin tesekkur ederiz.', 'GONDERILDI'),
    (5, 32, 'EMAIL', N'Emeklilik bilgilendirme sureciniz tamamlanmistir.', 'GONDERILDI'),
    (4, 35, 'SMS', N'Yaz kampanyamiza katiliminiz icin tesekkur ederiz.', 'GONDERILDI'),
    (5, 38, 'EMAIL', N'Emeklilik bilgilendirme sureciniz tamamlanmistir.', 'GONDERILDI'),
    (4, 41, 'SMS', N'Yaz kampanyamiza katiliminiz icin tesekkur ederiz.', 'GONDERILDI'),
    (5, 44, 'EMAIL', N'Emeklilik bilgilendirme sureciniz tamamlanmistir.', 'GONDERILDI'),
    (4, 47, 'SMS', N'Yaz kampanyamiza katiliminiz icin tesekkur ederiz.', 'GONDERILDI'),
    (5, 50, 'EMAIL', N'Emeklilik bilgilendirme sureciniz tamamlanmistir.', 'GONDERILDI'),
    (4, 53, 'SMS', N'Yaz kampanyamiza katiliminiz icin tesekkur ederiz.', 'GONDERILDI'),
    (5, 56, 'EMAIL', N'Emeklilik bilgilendirme sureciniz tamamlanmistir.', 'GONDERILDI'),
    (4, 59, 'SMS', N'Yaz kampanyamiza katiliminiz icin tesekkur ederiz.', 'GONDERILDI'),
    (5, 62, 'EMAIL', N'Emeklilik bilgilendirme sureciniz tamamlanmistir.', 'GONDERILDI'),
    (4, 65, 'SMS', N'Yaz kampanyamiza katiliminiz icin tesekkur ederiz.', 'GONDERILDI'),
    (5, 68, 'EMAIL', N'Emeklilik bilgilendirme sureciniz tamamlanmistir.', 'GONDERILDI'),
    (4, 71, 'SMS', N'Yaz kampanyamiza katiliminiz icin tesekkur ederiz.', 'GONDERILDI'),
    (5, 74, 'EMAIL', N'Emeklilik bilgilendirme sureciniz tamamlanmistir.', 'GONDERILDI'),
    (4, 77, 'SMS', N'Yaz kampanyamiza katiliminiz icin tesekkur ederiz.', 'GONDERILDI'),
    (5, 80, 'EMAIL', N'Emeklilik bilgilendirme sureciniz tamamlanmistir.', 'GONDERILDI'),
    (4, 83, 'SMS', N'Yaz kampanyamiza katiliminiz icin tesekkur ederiz.', 'GONDERILDI'),
    (5, 86, 'EMAIL', N'Emeklilik bilgilendirme sureciniz tamamlanmistir.', 'GONDERILDI'),
    (4, 89, 'SMS', N'Yaz kampanyamiza katiliminiz icin tesekkur ederiz.', 'GONDERILDI'),
    (5, 92, 'EMAIL', N'Emeklilik bilgilendirme sureciniz tamamlanmistir.', 'GONDERILDI'),
    (4, 95, 'SMS', N'Yaz kampanyamiza katiliminiz icin tesekkur ederiz.', 'GONDERILDI'),
    (5, 98, 'EMAIL', N'Emeklilik bilgilendirme sureciniz tamamlanmistir.', 'GONDERILDI'),
    (4, 101, 'SMS', N'Yaz kampanyamiza katiliminiz icin tesekkur ederiz.', 'GONDERILDI'),
    (5, 104, 'EMAIL', N'Emeklilik bilgilendirme sureciniz tamamlanmistir.', 'GONDERILDI'),
    (4, 107, 'SMS', N'Yaz kampanyamiza katiliminiz icin tesekkur ederiz.', 'GONDERILDI'),
    (5, 110, 'EMAIL', N'Emeklilik bilgilendirme sureciniz tamamlanmistir.', 'GONDERILDI'),
    (4, 113, 'SMS', N'Yaz kampanyamiza katiliminiz icin tesekkur ederiz.', 'GONDERILDI'),
    (5, 116, 'EMAIL', N'Emeklilik bilgilendirme sureciniz tamamlanmistir.', 'GONDERILDI');
